version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laraveluser
      DB_PASSWORD: yourpassword
    ports:
      - 8080:80
    volumes:
      - project:/var/www/html/laravel
    depends_on:
      - db
  db:
    image: mariadb:10.5
    volumes:
      - db_data:/var/lib/mysql
      - ./respaldo.sql:/docker-entrypoint-initdb.d/respaldo.sql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: yourpassword

volumes:
  db_data:
  project: